version: '4'
services:
  api-gateway:
    build: .
    container_name: api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - user-auth-service
      - movie-review-service
    networks:
      - app-network

  user-auth-service:
    build: ../user-auth-service
    container_name: user-auth-service
    ports:
      - "8081:8081"
    depends_on:
      - mysql
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/userdb
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=1999
    networks:
      - app-network

  movie-review-service:
    build: ../movie-review-service
    container_name: movie-review-service
    ports:
      - "8082:8082"
    depends_on:
      - mongo
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://root:password@mongo:27017/moviedb
    networks:
      - app-network

  mysql:
    image: mysql:8.3.0
    container_name: mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1999
      MYSQL_DATABASE: userdb
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
    networks:
      - app-network

  mongo:
    image: mongo:7.0.5
    container_name: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: moviedb
    volumes:
      - ./docker/mongodb/data:/data/db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge